# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160727_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='blog/static/css/imagenes/imagen1.png', upload_to='blog/static/subidas/img'),
        ),
        migrations.AddField(
            model_name='post',
            name='nombre_imagen',
            field=models.CharField(default='.png', max_length=80),
            preserve_default=False,
        ),
    ]
