# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160729_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categorias',
        ),
        migrations.AddField(
            model_name='post',
            name='url_post',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
